### ISSUE TITLE
How to outout structured in agent?

### ISSUE THREAD

**Issue by cpunion** [knowsuchagency/promptic#23]
In https://github.com/knowsuchagency/promptic/pull/21, these is a structured tools example: [examples/use_tools_structured.py](https://github.com/knowsuchagency/promptic/blob/0f50fac72060fcf3408d27ef131ea8b9451541ed/examples/use_tools_structured.py). As you can see, all tools outputs structured result, but the scheduler only outputs text, is there a way to make it outputs structured?

**Comment by knowsuchagency** [comment]
I don't think it's necessary to handle structured output from tools in the same way as functions decorated with `promptic` since the outputs of tools get fed to the llm, not the user. However, you can still get structured output from your agent. I integrated your examples in the test suite and demonstrated getting structured output [here](https://github.com/knowsuchagency/promptic/blob/57aaddd7c374bd179cc7b506800ab52c588eeb94/tests/test_promptic.py#L767)

**Comment by cpunion** [comment]
Thanks.
